In [1]:
import pymatgen as pmg
import numpy as np

First thing we generate the bulk $\mathrm{fcc}$ structure. 
* we define the lattice with the 3 fcc vectors
* a list with a symbol for the atoms in the structure ( in this just one Al) 
* the coordinates in the same order as the symbols is a list of np.arrays of length 3

In [2]:
alat = 10.21 
lattice = np.array([[0.,1.,1.], [1.,0.,1], [1.,1.,0]])* alat *0.5
species = ['Si','Si']
coords=[np.array([0,0,0]), np.array([0.25,0.25,0.25])]

s = pmg.Structure(lattice=lattice, species=species , coords=coords, coords_are_cartesian=False) 

just to check everything is fine we make print out the info about the structure

In [3]:
s

Structure Summary
Lattice
    abc : 7.219560235914651 7.219560235914651 7.219560235914651
 angles : 60.00000000000001 60.00000000000001 60.00000000000001
 volume : 266.08306525000006
      A : 0.0 5.105 5.105
      B : 5.105 0.0 5.105
      C : 5.105 5.105 0.0
PeriodicSite: Si (0.0000, 0.0000, 0.0000) [0.0000, 0.0000, 0.0000]
PeriodicSite: Si (2.5525, 2.5525, 2.5525) [0.2500, 0.2500, 0.2500]

we now generate a supercell with the $z$  axis oriented along the $[1 1 0]$ direction ant the other 2 axes perpendicular to it. 
* we copy the bulk structure into s1 
* we transform `sup1` in a supercell. The  input in the second line means that the new vectors of the lattice for the supercell are $$\bf{a_1^\prime} = \bf{a_3}-\bf{a_2}  \; ; \; \bf{a_2^\prime} = \bf{a_1} \: ; \: \bf{a_3^\prime} = \bf{a_3} + \bf{a_2} -\bf{a_1}  $$

In [4]:
sup1 = s.copy()
sup1.make_supercell([[0,-2,2],[1,0,0],[-1,1,1]], to_unit_cell = True)
sup1

Structure Summary
Lattice
    abc : 14.439120471829302 7.219560235914651 10.21
 angles : 90.0 90.0 90.0
 volume : 1064.3322610000002
      A : 0.0 10.21 -10.21
      B : 0.0 5.105 5.105
      C : 10.21 0.0 0.0
PeriodicSite: Si (0.0000, 5.1050, -5.1050) [0.5000, 0.0000, 0.0000]
PeriodicSite: Si (5.1050, 10.2100, -5.1050) [0.7500, 0.5000, 0.5000]
PeriodicSite: Si (0.0000, 0.0000, 0.0000) [0.0000, 0.0000, 0.0000]
PeriodicSite: Si (5.1050, 5.1050, 0.0000) [0.2500, 0.5000, 0.5000]
PeriodicSite: Si (2.5525, 7.6575, -2.5525) [0.5000, 0.5000, 0.2500]
PeriodicSite: Si (7.6575, 7.6575, -7.6575) [0.7500, 0.0000, 0.7500]
PeriodicSite: Si (2.5525, 2.5525, 2.5525) [0.0000, 0.5000, 0.2500]
PeriodicSite: Si (7.6575, 2.5525, -2.5525) [0.2500, 0.0000, 0.7500]

Now we need to transform the axes in order that $\bf{c}$ points in the $z$ direction.
The object `lattice` of pymatgen has all the info that we need. The 3 axis lengths $a,b,c$ and the angles between the axes $\alpha$ between b and c axes , $\beta$ between $\bf{a}$  and $\bf{c}$ and $\gamma$ between $\bf{a}$ and $\bf{b}$. 

We just set ${\bf c}^\prime = c \cdot \hat{\bf z}$; we then put ${\bf a}^\prime = a\cdot sin(\beta)\cdot \hat{\bf x} + a\cdot cos(\beta)\cdot\hat{\bf z}$ in the $xz$ plane forming an angle $\beta$ with ${\bf c}^\prime$; the components of $\mathbf{b}^\prime$ are found imposing that ${\bf b^\prime \cdot c^\prime} = b\,c\cdot cos(\alpha)$ and 
${\bf b^\prime \cdot a^\prime} = a\,b \cdot cos(\gamma)$

Just use this numbers to create the new vectors and print them to check we have done right

In [5]:
latt = sup1.lattice
a = latt.a ; alpha = latt.alpha*np.pi/180.0
b = latt.b ; beta = latt.beta*np.pi/180.0
c = latt.c ; gamma = latt.gamma *np.pi/180.0
print(a,b,c, alpha/np.pi*180, beta/np.pi*180, gamma/np.pi*180)
newa3 = c * np.array([0,0,1])
newa1 = a * np.array([np.sin(beta),0,np.cos(beta)])
ca = (np.cos(gamma) - np.cos(beta)*np.cos(alpha))/np.sin(beta)
cb = np.sqrt(np.sin(alpha)**2-ca**2)
newa2 = b * np.array([ca,cb,np.cos(alpha)])
newa1,newa2,newa3

14.439120471829302 7.219560235914651 10.21 90.0 90.0 90.0


(array([1.44391205e+01, 0.00000000e+00, 8.84141133e-16]),
 array([4.42070567e-16, 7.21956024e+00, 4.42070567e-16]),
 array([ 0.  ,  0.  , 10.21]))

now we replace these three axes in the structure.  then we print out structure info  to compare lengths, angles and fractional coordinates. 

In [6]:
sup1.lattice = pmg.Lattice(np.array([newa1, newa2,newa3]))
sup1

Structure Summary
Lattice
    abc : 14.439120471829302 7.219560235914651 10.21
 angles : 90.0 90.0 90.0
 volume : 1064.3322610000002
      A : 14.439120471829302 0.0 8.841411334164387e-16
      B : 4.4207056670821937e-16 7.219560235914651 4.4207056670821937e-16
      C : 0.0 0.0 10.21
PeriodicSite: Si (7.2196, 0.0000, 0.0000) [0.5000, 0.0000, 0.0000]
PeriodicSite: Si (10.8293, 3.6098, 5.1050) [0.7500, 0.5000, 0.5000]
PeriodicSite: Si (0.0000, 0.0000, 0.0000) [0.0000, 0.0000, 0.0000]
PeriodicSite: Si (3.6098, 3.6098, 5.1050) [0.2500, 0.5000, 0.5000]
PeriodicSite: Si (7.2196, 3.6098, 2.5525) [0.5000, 0.5000, 0.2500]
PeriodicSite: Si (10.8293, 0.0000, 7.6575) [0.7500, 0.0000, 0.7500]
PeriodicSite: Si (0.0000, 3.6098, 2.5525) [0.0000, 0.5000, 0.2500]
PeriodicSite: Si (3.6098, 0.0000, 7.6575) [0.2500, 0.0000, 0.7500]

Now that the c vector is  oriented along the z cartesian axis we can build any supercell along the $[110]$ direction of any the periodicity along the xy  plane and of any thickess along the z direction 

the first two vectors define the periodicity in the plane , the third vector the thickness. For example a $2\times2$ surface with thickness 3 is generated like this:

* first we generate the supercell 

In [22]:
sup2 = sup1.copy()
sup2.make_supercell([[1,0,0],[0,1,0],[0,0,10]], to_unit_cell = False)
sup2

Structure Summary
Lattice
    abc : 14.439120471829302 7.219560235914651 102.10000000000001
 angles : 90.0 90.0 90.0
 volume : 10643.322610000003
      A : 14.439120471829302 0.0 8.841411334164387e-16
      B : 4.4207056670821937e-16 7.219560235914651 4.4207056670821937e-16
      C : 0.0 0.0 102.10000000000001
PeriodicSite: Si (7.2196, 0.0000, 0.0000) [0.5000, 0.0000, 0.0000]
PeriodicSite: Si (7.2196, 0.0000, 10.2100) [0.5000, 0.0000, 0.1000]
PeriodicSite: Si (7.2196, 0.0000, 20.4200) [0.5000, 0.0000, 0.2000]
PeriodicSite: Si (7.2196, 0.0000, 30.6300) [0.5000, 0.0000, 0.3000]
PeriodicSite: Si (7.2196, 0.0000, 40.8400) [0.5000, 0.0000, 0.4000]
PeriodicSite: Si (7.2196, 0.0000, 51.0500) [0.5000, 0.0000, 0.5000]
PeriodicSite: Si (7.2196, 0.0000, 61.2600) [0.5000, 0.0000, 0.6000]
PeriodicSite: Si (7.2196, 0.0000, 71.4700) [0.5000, 0.0000, 0.7000]
PeriodicSite: Si (7.2196, 0.0000, 81.6800) [0.5000, 0.0000, 0.8000]
PeriodicSite: Si (7.2196, 0.0000, 91.8900) [0.5000, 0.0000, 0.9000]
PeriodicS

* then we extract the coordinates and order them along the z direction, in case we have different species we need to sort also the symbols .... 

In [23]:
coords = sup2.cart_coords
species = sup2.species
temp  = sorted(zip(species,coords), key= lambda x: x[1][2])
species = [_[0] for _ in temp ]
coords  = [_[1] for _ in temp ]
coords

[array([0., 0., 0.]),
 array([7.21956024e+00, 0.00000000e+00, 4.42070567e-16]),
 array([2.21035283e-16, 3.60978012e+00, 2.55250000e+00]),
 array([7.21956024, 3.60978012, 2.5525    ]),
 array([3.60978012, 3.60978012, 5.105     ]),
 array([10.82934035,  3.60978012,  5.105     ]),
 array([3.60978012, 0.        , 7.6575    ]),
 array([10.82934035,  0.        ,  7.6575    ]),
 array([ 7.21956024,  0.        , 10.21      ]),
 array([ 0.  ,  0.  , 10.21]),
 array([ 7.21956024,  3.60978012, 12.7625    ]),
 array([2.21035283e-16, 3.60978012e+00, 1.27625000e+01]),
 array([10.82934035,  3.60978012, 15.315     ]),
 array([ 3.60978012,  3.60978012, 15.315     ]),
 array([ 3.60978012,  0.        , 17.8675    ]),
 array([10.82934035,  0.        , 17.8675    ]),
 array([ 7.21956024,  0.        , 20.42      ]),
 array([ 0.  ,  0.  , 20.42]),
 array([ 7.21956024,  3.60978012, 22.9725    ]),
 array([2.21035283e-16, 3.60978012e+00, 2.29725000e+01]),
 array([10.82934035,  3.60978012, 25.525     ]),
 array(

* then we modify the periodicit along the a3 axes. We replace previous $\bf{c}$ vector with one that is longer than the lattice periodity in that direction this create a gap between the slabs. 

In [21]:
a1 = sup2.lattice.matrix[0]
a2 = sup2.lattice.matrix[1]
vacuum = 10 # length of the vacuum region 
a3 = sup2.lattice.matrix[2]+np.array([0.,0., vacuum])
surface = pmg.Structure(lattice = np.array([a1,a2,a3]), coords =coords, species= species, coords_are_cartesian=True)
from	collections import deque
it = (f"{_.specie.name}   {_.coords[0]:12.6f}  {_.coords[1]:12.6f}  {_.coords[2]:12.6f} \n" for _ in surface.sites) 
with open('posizioniSi100_20layer','w') as f:
	s = [" ".join((f"{round(_,6):12.6}" for _ in surface.lattice.matrix[i])) for i in [0,1,2]]    
	f.write ( "\n".join(s) + "\n")
	deque((f.write(_) for _ in it )) 
 

In [225]:
surface.to(filename='surf.cif')

In [226]:
p = surface.sites[4]

In [227]:
surface.lattice.matrix

array([[1.44391205e+01, 0.00000000e+00, 8.84141133e-16],
       [4.42070567e-16, 7.21956024e+00, 4.42070567e-16],
       [0.00000000e+00, 0.00000000e+00, 4.06300000e+01]])